name: Django Projects Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker-compose up -d
      run: Run Tests
    - name : Run Tests
      run : docker exec backend -c "flake8 && pytest ."
